name: CI for I am Ashish

on: 
  push: 
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Installing Packages
      run: npm install --progress=false
    - name: Building Code
      run: npm run build
